name: Android

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    android:
        runs-on: ubuntu-24.04
        name: Android

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Build for Android
                uses: skiptools/swift-android-action@main
                with:
                    swift-version: 6.1
